version: "3"

services:
    devmarkt:
        container_name: bivieh_devmarkt_dev
        build:
            context: .
            dockerfile: Dockerfile.debug
        volumes:
            - ./:/var/www/
        ports:
            - 8080:80
        env_file: .env
