version: "3"

services:
    devmarkt2:
        container_name: bivieh_devmarkt
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - 8080:80
        env_file: .env
