version: "3"

services:
    mysql:
        container_name: mysql_dev
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
    devmarkt:
        container_name: bivieh_devmarkt_dev
        build:
            context: .
            dockerfile: Dockerfile.debug
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/
        environment:
            MYSQL_HOST: mysql_dev
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            BOT_REDIRECT_URI: http://localhost:8080/login.php?
            BOT_BASE_URI: http://localhost:8080
        env_file: .env.dev
