#!/usr/bin/env bash

# Generate impressum and datenschutz from templates if they don't exist
if [ ! -f /var/www/public/impressum.html ]; then
    echo "Generating /var/www/public/impressum.html from template..."
    envsubst '${IMPRESSUM_NAME} ${IMPRESSUM_STREET} ${IMPRESSUM_CITY} ${IMPRESSUM_EMAIL}' \
        < /var/www/docker/templates/impressum.html.template \
        > /var/www/public/impressum.html
fi

if [ ! -f /var/www/public/datenschutz.html ]; then
    echo "Generating /var/www/public/datenschutz.html from template..."
    envsubst '${IMPRESSUM_NAME} ${IMPRESSUM_STREET} ${IMPRESSUM_CITY}' \
        < /var/www/docker/templates/datenschutz.html.template \
        > /var/www/public/datenschutz.html
fi

sed -i "s/Listen 80/Listen ${PORT:-80}/g" /etc/apache2/ports.conf
sed -i "s/:80/:${PORT:-80}/g" /etc/apache2/sites-enabled/*
apache2-foreground